name: Publicacion Automatica

on:
  push:
    tags:
      - "v*" # Se activa cuando creas una versi√≥n como v1.0

permissions:
  contents: write

jobs:
  build:
    name: Compilando para Android y Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Instalar dependencias
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Crear Release y Subir Archivos
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/x64/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
